### ISSUE TITLE
Sphero.cpp Coding Error

### ISSUE THREAD

**Issue by GDBNCD** [cmonr/Arduino-Sphero-Library#2]
Under the second if statement of the setMotorPowers, change it to say:

 if (p2 < 0){
        m2 = p2 * -1;
        dir2 = 0x02;
Instead of 
 if (p2 < 0){
        m1 = p2 * -1;
        dir2 = 0x02;

**Comment by cmonr** [comment]
Woah, can't believe that's existed for such a long time. Fixed: https://github.com/cmonr/Arduino-Sphero-Library/commit/5237192c2845fcd7767bda6996bdf2d709cf5578
